### ISSUE TITLE
希望支持IntelliJ IDEA 2024.2.x版本

### ISSUE THREAD

**Issue by Yegezw** [Nonoas/Bookmark-X#23]
希望能支持 IntelliJ IDEA 2024.2.x

**Comment by Nonoas** [comment]
> 希望能支持 IntelliJ IDEA 2024.2.x
好的，感谢您的建议

**Comment by Nonoas** [comment]
> 希望能支持 IntelliJ IDEA 2024.2.x

好的，感谢您的建议

**Comment by Nonoas** [comment]
已在 [release v2.0.3](https://github.com/Nonoas/Bookmark-X/releases/tag/v2.0.3) 支持
