### ISSUE TITLE
bookmark支持导入导出功能

### ISSUE THREAD

**Issue by Forwardxiang** [Nonoas/Bookmark-X#3]
你好，我最近由于在学习一些框架源码，经常要用到书签功能，而且我经常需要更换电脑，我想通过开发jetbrains插件的方式，将本地书签上传到自己的服务器，然后再需要的时候从服务器拉取，调研了很久，发现并没有完美的解决方案，似乎也没有人有相关需求。
       目前我是通过找到了bookmark本地的xml文件，并通过更改文件中的书签相关内容来实现这个功能的，但是在Windows平台有时候需要连续操作两次拉取才能生效，而在Mac平台只能关闭idea后，手动更改文件内容，再打开idea才能生效。
       实在找不到可以参考的资料了，看到您有bookmark插件开发经验，所以提一个issue碰碰运气😂
       最后：祝您工作顺利，一切安好！

**Comment by Nonoas** [comment]
有没有考虑过将书签的xml提交到git，使用书签导入导出的方式

**Comment by Nonoas** [comment]
> ```
>     你好，我最近由于在学习一些框架源码，经常要用到书签功能，而且我经常需要更换电脑，我想通过开发jetbrains插件的方式，将本地书签上传到自己的服务器，然后再需要的时候从服务器拉取，调研了很久，发现并没有完美的解决方案，似乎也没有人有相关需求。
>    目前我是通过找到了bookmark本地的xml文件，并通过更改文件中的书签相关内容来实现这个功能的，但是在Windows平台有时候需要连续操作两次拉取才能生效，而在Mac平台只能关闭idea后，手动更改文件内容，再打开idea才能生效。
>    实在找不到可以参考的资料了，看到您有bookmark插件开发经验，所以提一个issue碰碰运气😂
>    最后：祝您工作顺利，一切安好！
> ```

有没有考虑过将书签的xml提交到git，使用书签导入导出的方式

**Comment by Forwardxiang** [comment]
感谢回复😊，xml存储在哪不是问题，内容的解析和适配也不是问题，现在遇到的最大问题是，导入导出的体验问题，官方本身不支持导入导出，虽然可以自己写插件，但是奈何bookmark面板的数据只在工程启动时从xml加载一次，后续也只能从面板save all到xml，没法逆向更新，只能关掉idea，然后手动更改文件（或者你提到的git pull），再启动idea才会生效

**Comment by Forwardxiang** [comment]
也有尝试不操作xml文件，这样就能绕过这个需要重启工程的体验问题，直接操作面板数据相关实体，里面有很多参数需要调试，也没有注释，底层还是kotlin代码，完全找不到任何资料，，，无底洞😂

**Comment by Nonoas** [comment]
感谢您的建议，Bookmark-X会考虑基于现有添加的导入导出功能，如果您有兴趣也可以一同参与开发

**Comment by Nonoas** [comment]
> 也有尝试不操作xml文件，这样就能绕过这个需要重启工程的体验问题，直接操作面板数据相关实体，里面有很多参数需要调试，也没有注释，底层还是kotlin代码，完全找不到任何资料，，，无底洞😂

感谢您的建议，Bookmark-X会考虑基于现有添加的导入导出功能，如果您有兴趣也可以一同参与开发

**Comment by Nonoas** [comment]
该功能在 v1.1.1 完成
