### ISSUE TITLE
是否可以支持在标签结尾显示标签简要

### ISSUE THREAD

**Issue by codeleep** [Nonoas/Bookmark-X#4]
也就是在编辑器中。结尾显示。可以使用EditorLinePainter拓展来进行实现。最好可以设置开关是否显示

**Comment by codeleep** [comment]
https://github.com/Nonoas/Bookmark-X/pull/6 大佬CR一下，没问题合并合并

**Comment by Nonoas** [comment]
#7 实现此功能
